import { GameMapping } from "@/types/steam";

export const GameAlt: GameMapping[] = [
  {
    badId: "359550",
    goodId: "730",
    title: "Rainbow Six Siege",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Verified",
    rating: 5,
    genre: ["Shooter"],
    tags: ["FPS", "Tactical", "Competitive", "Military", "5v5", "Multiplayer"],
    antiCheat: {
      name: "BattlEye",
      status: "Broken",
      alternativeFix: "Counter-Strike 2 (VAC, Native Linux)",
    },
  },

  {
    badId: "valorant",
    goodId: "730",
    title: "Valorant",
    deckVerified: "Verified",
    badStatus: "Borked",
    goodStatus: "Native",
    rating: 4.8,
    genre: ["Shooter"],
    tags: ["FPS", "Tactical", "Competitive", "Military", "5v5", "Free to Play", "Hero Shooter"],
    antiCheat: {
      name: "Vanguard",
      status: "Kernel Hardlock",
      alternativeFix: "Counter-Strike 2 (VAC, Native Linux)",
    },
  },

  {
    badId: "359550",
    goodId: "440",
    title: "Rainbow Six Siege → Team Fortress 2",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Verified",
    rating: 5,
    genre: ["Shooter"],
    tags: ["FPS", "Tactical", "Military", "Competitive", "Team-Based", "Free to Play"],
    antiCheat: {
      name: "BattlEye",
      status: "Broken",
      alternativeFix: "VAC (Native)",
    },
  },

  {
    badId: "valorant",
    goodId: "440",
    title: "Valorant → Team Fortress 2",
    deckVerified: "Verified",
    badStatus: "Borked",
    goodStatus: "Native",
    rating: 4.8,
    genre: ["Shooter"],
    tags: ["FPS", "Tactical", "Competitive", "Military", "Free to Play", "Team-Based"],
    antiCheat: {
      name: "Vanguard",
      status: "Kernel Hardlock",
      alternativeFix: "Team Fortress 2 (VAC, Native Linux)",
    },
  },

  {
    badId: "league-of-legends",
    goodId: "570",
    title: "League of Legends → Dota 2",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["MOBA", "Strategy"],
    tags: ["Strategy", "5v5", "Fantasy", "Competitive", "Team-Based", "Free to Play"],
    antiCheat: {
      name: "Vanguard",
      status: "Kernel Hardlock",
      alternativeFix: "Dota 2 (Native Linux, Full Support)",
    },
  },

  {
    badId: "league-of-legends",
    goodId: "2437170",
    title: "League of Legends → Heroes of Mewerth",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["MOBA", "Strategy"],
    tags: ["Strategy", "5v5", "Fantasy", "Competitive", "Team-Based"],
    antiCheat: {
      name: "Vanguard",
      status: "Kernel Hardlock",
      alternativeFix: "Heroes of Newerth (Native Linux, Some Tweaks Required)",
    },
  },

  {
    badId: "league-of-legends",
    goodId: "heroes-of-newerth",
    title: "League of Legends",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Unknown",
    rating: 4.5,
    genre: ["MOBA", "Strategy"],
    tags: ["Strategy", "5v5", "Fantasy", "Competitive"],
    antiCheat: {
      name: "Vanguard",
      status: "Kernel Hardlock",
    },
    disclosure:
      "Heroes of Mewerth needs a little tweaks to working on linux. search the game in Lutris and download the linux version of the game.",
  },

  {
    badId: "2807960",
    goodId: "581320",
    title: "Battlefield 2042 → Insurgency: Sandstorm",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["Shooter"],
    tags: ["War", "Military", "Vehicles", "Large Scale", "Multiplayer", "FPS"],
    antiCheat: {
      name: "EA Anti-Cheat",
      status: "Incompatible",
      alternativeFix: "Insurgency: Sandstorm (Linux Support)",
    },
  },

  {
    badId: "1962663",
    goodId: "1172470",
    title: "Call of Duty: Warzone → Apex Legends Alternative",
    badStatus: "Borked",
    goodStatus: "Silver",
    deckVerified: "Unsupported",
    rating: 4.5,
    genre: ["Shooter"],
    tags: ["FPS", "Battle Royale", "Military", "Fast-Paced", "Competitive"],
    antiCheat: {
      name: "Ricochet",
      status: "Kernel Block",
      alternativeFix: "CS2 / Insurgency (Linux Compatible)",
    },
  },

  {
    badId: "578080",
    goodId: "548430",
    title: "PUBG: Battlegrounds → Deep Rock Galactic",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["Shooter"],
    tags: ["Co-op", "Mining", "Sci-Fi", "Native Linux", "Squad-based"],
    antiCheat: {
      name: "BattlEye",
      status: "Unstable",
      alternativeFix: "Deep Rock Galactic (Native Linux Support, Co-op Focus)",
    },
  },

  {
    badId: "fortnite",
    goodId: "548430",
    title: "Fortnite → Deep Rock Galactic",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Playable",
    rating: 4.2,
    genre: ["Shooter"],
    tags: ["Battle Royale", "Co-op", "Sci-Fi", "Native Linux", "Squad-based"],
    antiCheat: {
      name: "EAC / BattlEye",
      status: "Kernel Hardlock",
      alternativeFix: "Deep Rock Galactic (Native Linux, Squad-based Shooter)",
    },
  },

  {
    badId: "1085660",
    goodId: "553850",
    title: "Destiny 2",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Playable",
    rating: 4.7,
    genre: ["Shooter"],
    tags: ["FPS", "Sci-fi", "Loot", "Co-op", "Multiplayer", "RPG"],
    antiCheat: {
      name: "Bungie Anti-Cheat",
      status: "Unstable",
      alternativeFix: "Helldivers 2 (Proton Platinum)",
    },
  },

  {
    badId: "2195250",
    goodId: "1665460",
    title: "EA SPORTS FC 25",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["Sports"],
    tags: ["Soccer", "Football", "Simulation", "Multiplayer", "Competitive"],
    antiCheat: {
      name: "EA Anti-Cheat",
      status: "Incompatible",
      alternativeFix: "Proton Compatible / eFootball 2024",
    },
  },

  {
    badId: "2582560",
    goodId: "1760250",
    title: "EA SPORTS Madden NFL 25",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["Sports"],
    tags: ["American Football", "Football", "Simulation", "Multiplayer", "Competitive"],
    antiCheat: {
      name: "EA Anti-Cheat",
      status: "Incompatible",
      alternativeFix: "Front Office Football (Native Linux)",
    },
  },

  {
    badId: "3240220",
    goodId: "55230",
    title: "GTA VI → GTA V",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Playable",
    rating: 5,
    genre: ["Open World", "Action", "Adventure"],
    tags: ["Open World", "Action", "Multiplayer", "Crime", "Mature", "Shooter", "Sandbox"],
    disclosure:
      "GTA Online multiplayer uses BattlEye Anti-Cheat which is not enabled for Proton on Linux, blocking access to multiplayer mode on Linux and Steam Deck. Single-player works perfectly.",
    antiCheat: {
      name: "BattlEye AntiCheat",
      status: "Broken",
    },
  },

  {
    badId: "646910",
    goodId: "1551360",
    title: "Forza Horizon 4 → Horizon Chase 2",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Playable",
    rating: 4.5,
    disclosure:
      "This alternative applies to Forza Horizon series (4, 5, 6). These are Windows exclusive with BattlEye anti-cheat.",
    genre: ["Racing"],
    tags: ["Racing", "Open World", "Automobile Sim", "Multiplayer"],
    antiCheat: {
      name: "BattlEye AntiCheat",
      status: "Broken",
    },
  },

  {
    badId: "2537590",
    goodId: "2014780",
    title: "Microsoft Flight Simulator 2024 → FlightGear",
    badStatus: "Silver",
    goodStatus: "Native",
    deckVerified: "Unsupported",
    rating: 4.6,
    genre: ["Simulation", "Flight"],
    tags: ["Simulation", "Flight", "Realistic", "VR", "First-Person", "Military"],
    antiCheat: {
      name: "BattlEye AntiCheat",
      status: "Broken",
    },
  },

  {
    badId: "3932890",
    goodId: "252490",
    title: "Escape from Tarkov → Insurgency",
    badStatus: "Bronze",
    goodStatus: "Silver",
    deckVerified: "Unsupported",
    rating: 4.3,
    genre: ["Survival", "FPS"],
    tags: ["Extraction", "Hardcore", "FPS", "Loot", "Multiplayer", "Tactical"],
    antiCheat: {
      name: "BattlEye",
      status: "Unsupported",
      alternativeFix: "Insurgency: Sandstorm (Community Servers, Linux Native)",
    },
  },

  {
    badId: "yandere-simulator",
    goodId: "863550",
    title: "Yandere Simulator",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Verified",
    rating: 3.8,
    genre: ["Action", "Simulation"],
    tags: ["Single-player", "Stealth", "Indie", "Early Access"],
    disclosure:
      "Yandere Simulator is a unique indie title that has never been officially released on Steam. It exists as freeware. Runs on Linux through various community launchers and emulators with multiple tweaks required. Requires Proton Experimental or custom configurations.",
  },

  {
    badId: "genshin-impact",
    goodId: "2064650",
    title: "Genshin Impact",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Playable",
    rating: 4.6,
    genre: ["Action", "RPG", "Adventure"],
    tags: ["Open World", "RPG", "Gacha", "Action", "Adventure", "Fantasy", "Anime"],
    antiCheat: {
      name: "HoYoprotect (mhyprot2)",
      status: "Linux Supported",
      alternativeFix: "Runs natively via Proton Experimental",
    },
  },

  {
    badId: "1671200",
    goodId: "2064650",
    title: "Honkai Impact 3rd",
    badStatus: "Borked",
    goodStatus: "Silver",
    deckVerified: "Playable",
    rating: 4.4,
    genre: ["Action", "RPG"],
    tags: ["Action", "Anime", "Hack and Slash", "Female Protagonist", "Gacha", "Free to Play"],
    antiCheat: {
      name: "HoYoprotect (mhyprot2)",
      status: "Kernel Level",
      alternativeFix: "Proton-GE / Community Launcher",
    },
  },

  {
    badId: "honkai-star-rail",
    goodId: "2064650",
    title: "Honkai: Star Rail",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Unsupported",
    rating: 4.5,
    genre: ["RPG", "Strategy", "Adventure"],
    tags: ["Turn-Based Combat", "RPG", "Gacha", "Sci-Fi", "Anime", "Free to Play"],
    antiCheat: {
      name: "HoYoprotect (ACE)",
      status: "Kernel Hardlock",
      alternativeFix: "The Honkers Railway Launcher (Community)",
    },
  },

  {
    badId: "zenless-zone-zero",
    goodId: "2064650",
    title: "Zenless Zone Zero",
    badStatus: "Borked",
    goodStatus: "Silver",
    deckVerified: "Unsupported",
    rating: 4.3,
    genre: ["Action", "RPG"],
    tags: ["Action", "RPG", "Gacha", "Hack and Slash", "Urban Fantasy", "Free to Play", "Anime"],
    antiCheat: {
      name: "HoYoprotect",
      status: "Unstable / Blocked",
      alternativeFix: "Community Launcher / Waydroid (Android Subsystem)",
    },
  },

  {
    badId: "2488620",
    goodId: "1066890",
    title: "F1® 24",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Verified",
    rating: 4.4,
    genre: ["Racing", "Sports"],
    tags: ["Racing", "Formula 1", "Simulation", "Multiplayer", "Competitive"],
    antiCheat: {
      name: "EA Anti-Cheat",
      status: "Unsupported",
      alternativeFix: "rFactor 2 / Speed Dreams (Community Servers)",
    },
  },

  {
    badId: "227940",
    goodId: "236390",
    title: "Heroes & Generals",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Verified",
    rating: 4.2,
    genre: ["Shooter", "Strategy", "Military"],
    tags: [
      "Free to Play",
      "World War II",
      "FPS",
      "Multiplayer",
      "War",
      "Shooter",
      "Action",
      "First-Person",
      "Strategy",
      "Tactical",
      "Historical",
    ],
    antiCheat: {
      name: "BattlEye AntiCheat",
      status: "Unsupported",
      alternativeFix: "Post Scriptum / Squad (Community Servers)",
    },
  },
];