import { GameMapping } from "@/types/steam";

export const GameAlt: GameMapping[] = [
  {
    badId: "359550",
    goodId: "730",
    title: "Rainbow Six Siege",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Verified",
    rating: 5,
    genre: ["Shooter"],
    tags: ["FPS", "Tactical", "Competitive", "Military", "5v5"],
    antiCheat: {
      name: "BattlEye",
      status: "Broken",
      alternativeFix: "VAC (Native)",
    },
  },

  {
    badId: "valorant",
    goodId: "730",
    title: "Valorant",
    deckVerified: "Verified",
    badStatus: "Borked",
    goodStatus: "Native",
    rating: 4.8,
    genre: ["Shooter"],
    tags: ["FPS", "Tactical", "Competitive", "Military", "5v5", "Free to Play"],
    antiCheat: {
      name: "Vanguard",
      status: "Kernel Hardlock",
      alternativeFix: "Counter-Strike 2 (VAC, Native Linux)",
    },
  },

  {
    badId: "359550",
    goodId: "440",
    title: "Rainbow Six Siege",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Verified",
    rating: 5,
    genre: ["Shooter"],
    tags: ["FPS", "Tactical", "Military", "Competitive", "5v5"],
    antiCheat: {
      name: "BattlEye",
      status: "Broken",
      alternativeFix: "VAC (Native)",
    },
  },
  {
    badId: "valorant",
    goodId: "440",
    title: "Valorant",
    deckVerified: "Verified",
    badStatus: "Borked",
    goodStatus: "Native",
    rating: 4.8,
    genre: ["Shooter"],
    tags: ["FPS", "Tactical", "Competitive", "Military", "5v5", "Free to Play"],
    antiCheat: {
      name: "Vanguard",
      status: "Kernel Hardlock",
      alternativeFix: "Counter-Strike 2 (VAC, Native Linux)",
    },
  },

  {
    badId: "league-of-legends",
    goodId: "570",
    title: "League of Legends",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["MOBA", "Strategy"],
    tags: ["Strategy", "5v5", "Fantasy", "Competitive"],
    antiCheat: {
      name: "Vanguard",
      status: "Kernel Hardlock",
      alternativeFix: "Dota 2 (Native Linux)",
    },
  },

  {
    badId: "league-of-legends",
    goodId: "2437170",
    title: "League of Legends",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["MOBA", "Strategy"],
    tags: ["Strategy", "5v5", "Fantasy", "Competitive"],
    antiCheat: {
      name: "Vanguard",
      status: "Kernel Hardlock",
    },
  },

  {
    badId: "league-of-legends",
    goodId: "heroes-of-mewerth",
    title: "League of Legends",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Unknown",
    rating: 4.5,
    genre: ["MOBA", "Strategy"],
    tags: ["Strategy", "5v5", "Fantasy", "Competitive"],
    antiCheat: {
      name: "Vanguard",
      status: "Kernel Hardlock",
    },
    disclosure:
      "Heroes of Mewerth needs a little tweaks to working on linux. search the game in Lutris and download the linux version of the game.",
  },

  {
    badId: "2807960",
    goodId: "671860",
    title: "Battlefield 6",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["Shooter"],
    tags: ["War", "Destruction", "Military", "Vehicles", "Large Scale"],
    antiCheat: {
      name: "EA Anti-Cheat",
      status: "Incompatible",
      alternativeFix: "EAC (Linux Supported)",
    },
  },
  {
    badId: "1962663",
    goodId: "1172470",
    title: "Call of Duty",
    badStatus: "Borked",
    goodStatus: "Silver",
    deckVerified: "Unsupported",
    rating: 4.5,
    genre: ["Shooter"],
    tags: ["FPS", "Battle Royale", "Military", "Fast-Paced"],
    antiCheat: {
      name: "Ricochet",
      status: "Kernel Block",
      alternativeFix: "EAC (Linux Supported)",
    },
  },

  {
    badId: "578080",
    goodId: "1172470",
    title: "PUBG: BATTLEGROUNDS",
    badStatus: "Borked",
    goodStatus: "Silver",
    deckVerified: "Unsupported",
    rating: 4.5,
    genre: ["Shooter"],
    tags: ["Battle Royale", "Military", "Realistic", "FPS"],
    antiCheat: {
      name: "BattlEye",
      status: "Unstable",
      alternativeFix: "EAC (Linux Supported)",
    },
  },

  {
    badId: "fortnite",
    goodId: "1172470",
    title: "Fortnite",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Unsupported",
    rating: 4.2,
    genre: ["Shooter"],
    tags: [
      "Battle Royale",
      "Building",
      "Military",
      "Third-Person",
      "Free to Play",
    ],
    antiCheat: {
      name: "EAC / BattlEye",
      status: "Kernel Hardlock",
      alternativeFix: "Apex Legends (EAC Enabled)",
    },
  },

  {
    badId: "1085660",
    goodId: "553850",
    title: "Destiny 2",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Playable",
    rating: 4.7,
    genre: ["Shooter"],
    tags: ["FPS", "Sci-fi", "Loot", "Military", "Co-op"],
    antiCheat: {
      name: "Bungie Anti-Cheat",
      status: "Unstable",
      alternativeFix: "Helldivers 2 (Proton Platinum)",
    },
  },

  // {
  //   badId: "2456740",
  //   goodId: "4025700",
  //   title: "Inzo",
  //   badStatus: "Bronze",
  //   goodStatus: "Gold",
  //   deckVerified: "Playable",
  //   rating: 4.7,
  //   genre: ["Multiplayer", "Life Sim", "Simulation", "Third Person"],
  //   tags: [
  //     "Casual",
  //     "Life Sim",
  //     "Multiplayer",
  //     "Free to Play",
  //     "Cute",
  //     "Artificial Intelligence",
  //     "City Builder",
  //     "Relaxing",
  //     "Immersive Sim",
  //     "Simulation",
  //     "3D Platformer",
  //     "Character Customization",
  //     "Cartoony",
  //     "Third Person",
  //     "Funny",
  //     "Realistic",
  //     "Nature",
  //     "Singleplayer",
  //     "Atmospheric",
  //     "Story Rich",
  //   ],
  // },

  {
    badId: "2195250",
    goodId: "1665460",
    title: "EA SPORTS FC 24",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["Sports"],
    tags: ["Soccer", "Football", "Simulation"],
    antiCheat: {
      name: "EA Anti-Cheat",
      status: "Incompatible",
      alternativeFix: "Proton Compatible",
    },
  },
  {
    badId: "2582560",
    goodId: "1760250",
    title: "EA SPORTS Madden NFL 25",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Playable",
    rating: 4.5,
    genre: ["Sports"],
    tags: ["Soccer", "American Football", "Simulation"],
    antiCheat: {
      name: "EA Anti-Cheat",
      status: "Incompatible",
      alternativeFix: "Proton Compatible",
    },
  },

  // {
  //   badId: "1599340",
  //   goodId: "238960",
  //   title: "Lost Ark",
  //   badStatus: "Bronze",
  //   goodStatus: "Silver",
  //   rating: 4.5,
  //   genre: ["RPG"],
  //   tags: ["MMO", "ARPG", "Loot", "Isometric"],
  //   antiCheat: {
  //     name: "Easy Anti-Cheat",
  //     status: "Not Enabled",
  //     alternativeFix: "Native / Vulkan",
  //   },
  // },

  {
    badId: "3240220",
    goodId: "55230",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Playable",
    genre: ["Open World", "Third-Person", "Vehicles"],
    tags: [
      "Open World",
      "Action",
      "Sexual Content",
      "Multiplayer",
      "Crime",
      "Mature",
      "Shooter",
      "Third Person",
      "First-Person",
      "Adventure",
      "Automobile Sim",
      "Racing",
      "Third-Person Shooter",
      "Sandbox",
      "Funny",
      "Atmospheric",
      "Comedy",
      "Moddable",
      "PvP",
      "Co-op",
    ],
    title: "GTA V",
    rating: 5,
    disclosure:
      "GTA Online's implementation of BattlEye Anti-Cheat is currently not enabled for Proton, preventing access to multiplayer on Linux and Steam Deck.",
    antiCheat: {
      name: "BattlEye AntiCheat",
      status: "Broke",
    },
  },

  {
    badId: "646910",
    goodId: "1551360",
    title: "The Crew 2",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Playable",
    disclosure:
      "This Alternative applied to Forza Horizon 4 and wait for further news about Forza Horizon 6 linux support",
    genre: ["Racing"],
    tags: ["Racing", "Open World", "Automobile Sim"],
    antiCheat: {
      name: "BattlEye AntiCheat",
      status: "Broke",
    },
  },

  {
    badId: "2537590",
    goodId: "2014780",
    title: "Microsoft Flight Simulator 2024",
    badStatus: "Silver",
    goodStatus: "Native",
    deckVerified: "Unsupported",
    genre: ["Simulation", "Flight", "First-Person", "Military", "Vehicles"],
    tags: [
      "Simulation",
      "Flight",
      "Realistic",
      "VR",
      "3D",
      "Immersive Sim",
      "Action-Adventure",
      "3D Vision",
      "First-Person",
      "Jet",
      "Atmospheric",
      "Military",
      "Controller",
      "Relaxing",
      "Choices Matter",
      "Moddable",
      "Open World",
      "Physics",
      "Tutorial",
      "Co-op",
    ],
    antiCheat: {
      name: "BattlEye AntiCheat",
      status: "Broke",
    },
  },

  {
    badId: "3932890",
    goodId: "252490",
    title: "Escape from Tarkov",
    badStatus: "Bronze",
    goodStatus: "Silver",
    deckVerified: "Unsupported",
    genre: ["Survival"],
    tags: ["Extraction", "Hardcore", "FPS", "Loot"],
    antiCheat: {
      name: "BattlEye",
      status: "Unsupported",
      alternativeFix: "EAC (Community Servers)",
    },
  },

  {
    badId: "yandere-simulator",
    goodId: "2527500",
    title: "Yandere Simulator",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Playable",
    genre: ["Action", "Simulation", "Single-player"],
    tags: ["Single-player", "Stealth"],
    disclosure:
      "Yandere Simulator is a unique indie title that has never been available on Steam. And to work it needs many tweaks to work on linux. There is no official statement about working the game on linux from the developer.",
  },

  {
    badId: "genshin-impact",
    goodId: "2064650",
    title: "Genshin Impact",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Playable",
    genre: ["Action", "RPG", "Adventure"],
    tags: ["Open World", "RPG", "Gacha", "Action", "Adventure", "Fantasy"],
    antiCheat: {
      name: "HoYoprotect (mhyprot2)",
      status: "Linux Supported",
      alternativeFix: "Runs natively via Proton Experimental",
    },
  },

  {
    badId: "1671200",
    goodId: "2064650",
    title: "Honkai Impact 3rd",
    badStatus: "Borked",
    goodStatus: "Silver",
    deckVerified: "Playable",
    genre: ["Action", "RPG", "Free to Play"],
    tags: ["Action", "Anime", "Hack and Slash", "Female Protagonist", "Gacha"],
    antiCheat: {
      name: "HoYoprotect (mhyprot2)",
      status: "Kernel Level",
      alternativeFix: "Proton-GE / Community Launcher",
    },
  },

  {
    badId: "honkai-star-rail",
    goodId: "2064650",
    title: "Honkai: Star Rail",
    badStatus: "Borked",
    goodStatus: "Gold",
    deckVerified: "Unsupported",
    genre: ["RPG", "Strategy", "Adventure"],
    tags: ["Turn-Based Combat", "RPG", "Gacha", "Sci-Fi", "Anime"],
    antiCheat: {
      name: "HoYoprotect (ACE)",
      status: "Kernel Hardlock",
      alternativeFix: "Use 'The Honkers Railway Launcher' (Community)",
    },
  },

  {
    badId: "zenless-zone-zero",
    goodId: "2064650",
    title: "Zenless Zone Zero",
    badStatus: "Borked",
    goodStatus: "Silver",
    deckVerified: "Unsupported",
    genre: ["Action", "RPG"],
    tags: ["Action", "RPG", "Gacha", "Hack and Slash", "Urban Fantasy"],
    antiCheat: {
      name: "HoYoprotect",
      status: "Unstable / Blocked",
      alternativeFix: "Community Launcher / Waydroid (Android Subsystem)",
    },
  },

  {
    badId: "yandere-simulator",
    goodId: "863550",
    title: "Yandere Simulator",
    badStatus: "Borked",
    goodStatus: "Platinum",
    deckVerified: "Verified",
    genre: ["Action", "Simulation", "Single-player"],
    tags: ["Single-player", "Stealth"],
    disclosure:
      "Yandere Simulator is a unique indie title that has never been available on Steam. And to work it needs many tweaks to work on linux. There is no official statement about working the game on linux from the developer.",
  },

  {
    badId: "2488620",
    goodId: "1066890",
    title: "F1® 24",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Verified",
    genre: ["Racing", "Sports"],
    tags: ["Racing", "Formula 1", "Simulation"],
    antiCheat: {
      name: "EA Anti-Cheat",
      status: "Unsupported",
      alternativeFix: "EAC (Community Servers)",
    },
  },
  {
    badId: "227940",
    goodId: "236390",
    title: "Heroes & Generals",
    badStatus: "Borked",
    goodStatus: "Native",
    deckVerified: "Verified",
    genre: ["Shooter", "Strategy", "Military"],
    tags: [
      "Free to Play",
      "World War II",
      "FPS",
      "Multiplayer",
      "War",
      "Shooter",
      "Action",
      "First-Person",
      "Massively Multiplayer",
      "Strategy",
      "Tactical",
      "Co-op",
      "Historical",
      "Open World",
      "Simulation",
      "Atmospheric",
      "Adventure",
      "Indie",
      "RTS",
    ],
    antiCheat: {
      name: "BattlEye AntiCheat",
      status: "Unsupported",
      alternativeFix: "EAC (Community Servers)",
    },
  },
];
